# Please see the documentation for all configuration options:
# https://docs.github.com/en/enterprise-cloud@latest/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target: "dev"
    ignore:
      - dependency-name: "@dfinity/*"
      - dependency-name: "@types/*"
      - dependency-name: "@typescript-eslint/*"
      - dependency-name: "eslint"
      - dependency-name: "eslint-*"
      - dependency-name: "sass"
      - dependency-name: "svelte"
      - dependency-name: "typescript"
      - dependency-name: "vite"