name: Build Oisy backend Wasm

description: An action that provides Oisy backend Wasm

outputs: {}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache backend wasm
      uses: actions/cache@v4
      id: backend-wasm-cache
      with:
        path: |
          target/wasm32-unknown-unknown/release/backend.wasm
        key: backend-wasm-${{ hashFiles('Cargo.toml', 'Cargo.lock', 'rust-toolchain.toml', 'src/backend/**/*', 'src/shared/**/*') }}

    - name: Build Base Docker Image
      if: steps.backend-wasm-cache.outputs.cache-hit != 'true'
      uses: ./.github/actions/docker-build-base

    - name: Build canister WASM
      if: steps.backend-wasm-cache.outputs.cache-hit != 'true'
      uses: ./.github/actions/docker-build-backend
      with:
        name: backend.wasm.gz
        target: scratch_backend