name: Deploy Backend

description: Build and deploy the backend after having installed dfx

# TODO: improve this action, caching the built Cargo packages, maybe with Docker

runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore cargo cache
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.cargo/registry
          /home/runner/.cargo/git
          target/
          ~/.cargo/bin/
        key: ${{ runner.os }}-e2e-cargo-${{ hashFiles('Cargo.toml', 'Cargo.lock', 'rust-toolchain.toml', 'src/backend/**/*', 'src/shared/**/*') }}
        restore-keys: |
            ${{ runner.os }}-e2e-cargo-

    - name: Prepare
      uses: ./.github/actions/prepare

    - name: Install dfx
      uses: dfinity/setup-dfx@main

    - name: Start dfx
      shell: bash
      run: dfx start --background --quiet

    - name: Install LLVM on macOS
      if: runner.os == 'macOS'
      run: brew install llvm

    - name: Set environment variables for wasm32 target on macOS
      if: runner.os == 'macOS'
      run: |
        echo "CC_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
        echo "AR_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/llvm-ar" >> $GITHUB_ENV
        echo "CFLAGS_wasm32_unknown_unknown=--target=wasm32-unknown-unknown" >> $GITHUB_ENV
        echo "CRATE_CC_NO_DEFAULTS=true" >> $GITHUB_ENV

    - name: Deploy backend
      shell: bash
      run: npm run deploy
