name: Deploy Backend

description: Build and deploy the backend after having installed dfx

# TODO: improve this action, caching the built Cargo packages, maybe with Docker

runs:
  using: "composite"
  steps:
  
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore npm cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

    - name: Restore cargo cache
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/.cargo/registry
          /home/runner/.cargo/git
          target/
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
            ${{ runner.os }}-cargo-

    - name: Prepare
      uses: ./.github/actions/prepare

    - name: Install dfx
      uses: dfinity/setup-dfx@main

    - name: Start dfx
      shell: bash
      run: dfx start --background --quiet

    - name: Deploy backend
      shell: bash
      run: npm run deploy
