name: 'Setup LLVM and Bash on macOS'
description: 'Installs LLVM and Bash 5 on macOS and sets up environment variables for wasm32 target'

inputs:
  os:
    description: 'Operating system (e.g., ubuntu-latest, macos-latest)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install LLVM and Bash on macOS
      if: ${{ inputs.os == 'macos-latest' }}
      shell: bash
      run: |
        brew install llvm
        brew install bash
    - name: Add Bash 5 to PATH on macOS
      if: ${{ inputs.os == 'macos-latest' }}
      shell: bash
      run: |
        echo "$(brew --prefix bash)/bin" >> $GITHUB_PATH
    - name: Verify Bash Version
      if: ${{ inputs.os == 'macos-latest' }}
      shell: bash
      run: |
        bash --version
    - name: Set environment variables for wasm32 target on macOS
      if: ${{ inputs.os == 'macos-latest' }}
      shell: bash
      run: |
        echo "CC_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
        echo "AR_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/llvm-ar" >> $GITHUB_ENV
        echo "CFLAGS_wasm32_unknown_unknown=--target=wasm32-unknown-unknown" >> $GITHUB_ENV
        echo "CRATE_CC_NO_DEFAULTS_wasm32_unknown_unknown=true" >> $GITHUB_ENV
