name: Backend tests

on:
  pull_request:
    paths:
      - 'src/backend/**'
      - 'src/shared/**'

jobs:

  docker-build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Base Docker Image
        uses: ./.github/actions/docker-build-base

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-build-base
    strategy:
      matrix:
        include:
          - name: backend.wasm.gz
            target: scratch_backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build canister WASM
        uses: ./.github/actions/docker-build-backend
        with:
          name: ${{ matrix.name }}
          target: ${{ matrix.target }}

  may-merge:
    needs: [ 'docker-build' ]
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK