name: Backend Checks

on:
  pull_request:
    paths:
      - # Scripts, GitHub actions that contain 'backend' in their path.
        '**/*backend*'
      - # The backend source code
        'src/backend/**'
      - 'src/shared/**'
      - # Rust files such as Cargo.lock, Cargo.toml and rust-toolchain.toml
        '**/Cargo*'
      - '**/*rust*'
      - # The dockerfile used in this CI run, and the scripts it COPY's.
        'Dockerfile'
      - 'docker/**'
  workflow_dispatch:

jobs:

  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-backend-tests-${{ hashFiles('Cargo.lock', 'rust-toolchain.toml') }}
      - name: Print hello world
        run: cargo run --bin oisy

  may-merge:
    needs: [ 'hello-world' ]
    runs-on: ubuntu-20.04
    steps:
      - name: Cleared for merging
        run: echo OK
