name: E2E Tests

on:
  pull_request:
    paths:
      - 'e2e/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  oisy-backend-wasm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build oisy-backend WASM
        uses: ./.github/actions/oisy-backend

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    needs: oisy-backend-wasm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM on macOS
        if: runner.os == 'macOS'
        run: brew install llvm
  
      - name: Set environment variables for wasm32 target on macOS
        if: runner.os == 'macOS'
        run: |
          echo "CC_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "AR_wasm32_unknown_unknown=$(brew --prefix llvm)/bin/llvm-ar" >> $GITHUB_ENV
          echo "CFLAGS_wasm32_unknown_unknown=--target=wasm32-unknown-unknown" >> $GITHUB_ENV
          echo "CRATE_CC_NO_DEFAULTS=true" >> $GITHUB_ENV

      - name: Deploy the backend
        uses: ./.github/actions/deploy-backend

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Test
        run: npm run e2e:ci

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  may-merge-e2e:
    needs: ['e2e']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    steps:
      - name: Cleared for merging
        run: echo OK
