name: E2E Tests

on:
  pull_request:
    paths:
      - 'e2e/**'
  workflow_dispatch:

jobs:

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download E2E Docker image artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: e2e-tests-build-docker-image.yml
          name: oisy-e2e-image
          branch: main
          if_no_artifact_found: fail

      - name: Load Docker image
        run: |
          gzip -d oisy-e2e-image.tar.gz
          docker load -i oisy-e2e-image.tar

      - name: Run E2E Docker container
        run: |
          docker run -d -p 4943:4943 --name oisy-e2e-container oisy-e2e-image:latest

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Test
        run: npm run e2e:ci

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Cleanup Docker container
        run: |
          docker stop oisy-e2e-container
          docker rm oisy-e2e-container

  may-merge:
    needs: ['e2e']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
