name: Formatting Checks

on:
  pull_request:
  workflow_dispatch:

jobs:

  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install shfmt
        run: sudo snap install --classic shfmt
      - name: Install cargo dependency sorter
        run: cargo install cargo-sort@1.0.9
      - name: Format
        run: ./scripts/format.sh
      - name: Check formatted
        run: |
          test -z "$(git status --porcelain)" || {
                  echo "FIX: Please run ./scripts/format.sh"
                  git diff
                  exit 1
          }
