name: E2E Tests

on:
  pull_request:
    paths:
      - 'e2e/**'
  workflow_dispatch:

env:
  RUNNER_OS: ubuntu-20.04

jobs:

  docker-build-e2e:
    runs-on: ${{ env.RUNNER_OS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Base Docker Image
        uses: ./.github/actions/docker-build-base

  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Test
        run: npm run test

  may-merge:
    needs: ['e2e']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
