name: Tag and Release on Merge from Release Branch

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'chore(release)/v')
    runs-on: ubuntu-24.04

    steps:
    - name: Create GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
        private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare
      uses: ./.github/actions/prepare

    - name: Get version from package.json
      id: get_version
      run: |
        version=$(node -p "require('./package.json').version")
        echo "Version from package.json: $version"
        echo "version=$version" >> $GITHUB_OUTPUT
  
    - name: Create Git tag
      run: |
        git tag "v${{ steps.get_version.outputs.version }}"
        git push origin "v${{ steps.get_version.outputs.version }}"

    - name: Publish Release Notes
      id: publish_release
      uses: release-drafter/release-drafter@v6
      with:
        version: "v${{ steps.get_version.outputs.version }}"
        token: ${{ steps.app-token.outputs.token }}
        tag: 'v${{ steps.get_version.outputs.version }}'
        name: 'v${{ steps.get_version.outputs.version }}'
        latest: true
        publish: true
