name: Update E2E Snapshots

on:
  workflow_dispatch:

jobs:

  update_snapshots:
    runs-on: ubuntu-latest
    needs: docker-build-e2e
    steps:
      - name: Fail if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on main"
          exit 1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download E2E Docker image artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: e2e-tests-build-docker-image.yml
          name: oisy-e2e-image
          branch: main
          if_no_artifact_found: fail

      - name: Load Docker image
        run: |
          gzip -d oisy-e2e-image.tar.gz
          docker load -i oisy-e2e-image.tar

      - name: Run E2E Docker container
        run: |
          docker run -d -p 4943:4943 --name oisy-e2e-container oisy-e2e-image:latest

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Run Playwright tests
        run: npm run e2e:snapshots

      - name: Commit Playwright updated snapshots
        uses: EndBug/add-and-commit@v9
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          add: e2e
          default_author: github_actions
          message: "🤖 update E2E snapshots"
